### ISSUE TITLE
[Bug] openssl.exe is not found

### ISSUE THREAD

**Issue by tobiasbenkner** [node-opcua/node-opcua-pki#11]
Hi,

i cannot run ```npm run postinstall``` because the url is not available https://github.com/node-opcua/node-opcua-pki/files/1886617/openssl-1.0.2o-x64_86-win64.zip

greets

**Comment by erossignon** [comment]
what version of node-opcua-pki are you using ?

**Comment by Tom-Simon** [comment]
Hello, I'm experiencing the same problem over different versions.
It guess the process downloading the zip file isn't using the proxy settings provided with npm.

**Comment by erossignon** [comment]
@Tom-Simon can you verify that node-opcua-pki installed well behind a proxy now with version `node-opcua-pki@2.0.4` ?
you may have to setup the HTTP_PROXY environment variable prior running `npm install`

**Comment by Tom-Simon** [comment]
Ok, forget what I said, while npm is correctly using my proxy settings, nodeJS is not aware of the environment variable.
The other module listed below was on another PC configred differently.
Console log was missing due to process.env.https_proxy beeing undefined in my environment. Will fix that and check again.


----old entry---
Hello and thanks for the fast response @erossignon .
Unfortunatly it is still not working for me. I'm running behind a corporate proxy that is configured in npm as https-proxy and proxy environment variable and is available inside node as process.env.https_proxy, but I'm not seeing the log entry -" using proxy" for some unknown reason.

![image](https://user-images.githubusercontent.com/60611325/86249998-500eb200-bbb0-11ea-99cc-0f22be3f9206.png)

I have another module where the proxy is successfully used though via

`
client = Client.fromConnectionString(clientConnectionString, Protocols[clientProtocol]);
if(process.env.https_proxy) {
 var HttpsProxyAgent = require('https-proxy-agent');
 client.setOptions({
  http: {
    agent: new HttpsProxyAgent(process.env.https_proxy)
  },
`

**Comment by tobiasbenkner** [comment]
the problem i had was, that the assets/binaries were not stored in the github anymore. currently only the source files are there. therefore the link https://github.com/node-opcua/node-opcua-pki/files/1886617/openssl-1.0.2o-x64_86-win64.zip went nowhere. this has nothing to do with the proxy settings.

i solved the problem by copying the openssl.exe from the git installation to the appropriate path where it is needed.

**Comment by erossignon** [comment]
@tobiasbenkner you must be using a very old version of node-opcua-pki . Have you tried updating the package version number to the most recent one ?

**Comment by tobiasbenkner** [comment]
at the moment, we are using the version "node-opcua-pki": "^1.5.5". I'm fine with the workaround to place openssl.exe to the correct folder

```
cp "C:\Program Files\Git\usr\bin\openssl.exe" "C:\Users\{{windows_user}}\AppData\Local\Programs\openssl\openssl.exe"
````
