### ISSUE TITLE
pki subfolder "issuers" instead of "issuer"

### ISSUE THREAD

**Issue by nobodyman1** [node-opcua/node-opcua-pki#26]
The [OPC UA specification](https://reference.opcfoundation.org/GDS/docs/F.1/) shows following directory layout for the issuer certificates:
<html><body>

<root>/issuer | The Certificate store which contains the CA Certificates needed for validation.
-- | --
<root>/issuer/certs | Contains the X.509 v3 Certificates which are needed for validation.
<root>/issuer/crl | Contains the X.509 v3 CRLs for any Certificates in the ./certs directory.

</body>
</html>

But the modules uses "issuers" (additional `s`) in [certificate_manager.ts](https://github.com/node-opcua/node-opcua-pki/blob/e30d9918838917c966d2bc1d22f62142fa233f04/lib/pki/certificate_manager.ts#L319).

**Comment by erossignon** [comment]
Interesting. 
It seems that UAExpert is also using `issuers` with a `s` instead of `issuer`.

The CTT certification platform from the OPC Foundation is also naming this folder `issuers`

We might want to raise this issue at the OPC Foundation Technical committee for review.
![image](https://user-images.githubusercontent.com/680220/160236873-3e731ed9-31b8-4590-8f5b-7b908b5cf3df.png)

There will be multiple issuer's certificates in this folder so using plural makes sense.

**Comment by erossignon** [comment]
I am inclined not to change anything for the moment until this issue is addressed by the committee, as this would involve breaking changes.

**Comment by erossignon** [comment]
I have raised a mantis issue for the OPC Foundation TAC : https://mantis.opcfoundation.org/view.php?id=7895

**Comment by erossignon** [comment]
Here is the answer  from the OPC working group:


> The spec currently matches the implementation of the LDS for which this path is normative. For all other implementations, the path is a non-normative recommendation.


Therefore, we will stick with the crowd and use the plural convention ( "issuers") like in Prosys, Unified Automation and many more implementatione.
